language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --dev --no-interaction --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit
